server:
  port: 7007
  servlet:
    context-path: /csp-producer

spring:
  application:
    name: csp-producer
  kafka:
    bootstrap-servers: localhost:9092
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

csp:
  topic-name: csp-topic
